name: Test

on:
  push:
    paths:
      - 'tracker/**'
  pull_request:
    paths:
      - 'tracker/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracker

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
          cache-dependency-path: tracker/yarn.lock

      - run: yarn install --immutable

      - run: yarn test
