name: Test

on:
  push:
    paths:
      - 'tracker/**'
      - 'fetch-server/**'
  pull_request:
    paths:
      - 'tracker/**'
      - 'fetch-server/**'

jobs:
  test-tracker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tracker

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: yarn-${{ hashFiles('tracker/yarn.lock') }}

      - run: yarn install --immutable

      - run: yarn test

  test-fetch-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fetch-server

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: pytest
